name: Version Bump on PR
on:
    pull_request_review:
        types:
            - submitted
            - edited
jobs:
    version_bump_check:
        runs-on: ubuntu-latest
        steps:
            - id: 'reviews'
              uses: 'jrylan/github-action-reviews-counter@main'
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
            -  # Conditionally run the next step
            - if: 'steps.reviews.outputs.approved >= 2 && steps.reviews.outputs.changes_requested == 0'
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            - if: 'steps.reviews.outputs.approved >= 2 && steps.reviews.outputs.changes_requested == 0'
              name: Bump version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
                  yarn version --patch --message "[Bot] Bumped version to %s"
                  git push
